### PR TITLE
Handle autoLoad response, hook callbacks default implementation

### PR DESCRIPTION
**Pull request by dulyts**
In my application after autoLoad I can't create redux action based-on `loaded` or `onSuccess` so I create `onAutoLoadFinished` to decide user is logged in or not.

### CODE REVIEW

**Comment by dulyts** [comment]
@anthonyjgrove could you check my solution please?

**Comment by anthonyjgrove** [comment]
Can you explain why you can't use `handleSigninSuccess`?  That being said, i did notice a bug in the master branch code https://github.com/anthonyjgrove/react-google-login/blob/master/src/use-google-login.js#L106, that i can fix.

**Comment by dulyts** [comment]
`handleSigninSuccess` don't called after autoLoad if user is not logged in.

**Comment by dulyts** [comment]
My useGoogleLogin usage: 
```javascript
const { signIn } = useGoogleLogin({
    clientId: process.env.REACT_APP_OAUTH_GOOGLE_CLIENT_ID,
    onSuccess: response => dispatch({ type: 'AUTH_SUCCESS', user: response.profileObj }),
    onFailure: error => dispatch({ type: 'AUTH_FAILURE', error }),
    onAutoLoadFinished: (success) => {
        if (!success)  dispatch({ type: 'AUTH_NOT_LOGGED_IN' })
    },
    isSignedIn: true,
});
```

**Comment by dulyts** [comment]
@anthonyjgrove Do you have any objections to the change request?

**Pull request merged**
