### PR TITLE
added authentication reload after a specified amount of time

### PR DESCRIPTION
**Pull request by applike-ss**
We needed the ability to do an authentication reload frontend wise which is a supplied functionality by googles auth2 client.

### CODE REVIEW

**Comment by applike-ss** [comment]
@anthonyjgrove can you take a closer look?

**Comment by anthonyjgrove** [comment]
If you can fix the conflicts I can try to get this merged in this week.

**Comment by anthonyjgrove** [comment]
And can you elaborate more on the use case just to make sure i fully understand.

**Comment by applike-ss** [comment]
We were having issues with the access token running out after one hour. For that reason we implemented a logic, that can be triggered in a time interval to reauth via the google auth2 api client and return the result to the parent component. This is needed if you want to have the most recent access_token etc. in your application using this component.

**Comment by applike-ss** [comment]
@anthonyjgrove can we somehow directly communicate? I would rather not want to rebase 10 times and still not have it merged. This would help me have this done.

**Comment by anthonyjgrove** [comment]
It just ended up putting me in an infinite loop when i set `authReloadInterval={100}` in the demo component which will need to be addressed.  Maybe the interval should be a fixed to an hour?  Also update the readme to include instructions

```
 <GoogleLogin onSuccess={success} onFailure={error} clientId={clientId} authReloadInterval={100} />
```

**Comment by applike-ss** [comment]
You are right, trying to reload 10 times a second is not really a good idea :wink:. I would suggest to rather use something like 14-18 minutes, so that there is enough room for failures until the access token expires.

**Comment by applike-ss** [comment]
I will not be available for the next two weeks.
@anthonyjgrove Can we communicate via any kind of chat in two weeks, so we can get this merged? It seems to me, that you configured this in your example in a wrong way.

**Comment by anthonyjgrove** [comment]
Yes it was obviously configured wrong, my suggestion is that you just make the auto refresh interval a fixed value to the life of the token returned by google.

**Comment by bln-engaged** [comment]
This pull request should address the concerns raised in previously closed issue #89 and #175. Anything I can do to help resolve things here and get this pull request merged? I am working through the same refresh issue and would love to have the support integrated instead of hoop jumping.

**Comment by FamishedDragon** [comment]
I would love to see this make it in as well

**Comment by chitgoks** [comment]
what's the final solution for this one? I do not see any authReloadInterval  in google-login.js

**Comment by bionicles** [comment]
Would like to use this so users don't have to sign in over and over and over

**Comment by applike-ss** [comment]
@anthonyjgrove i don't see why the value should be fixed. Since we don't do any kind of retry logic here and since users in different environments might switch networks quite frequently (which interrupts their ability to refresh the token while offline). Having this configurable enables the developer or depending on implementation even the platform administrator to adjust according to needs. If you want, i can try to rebase it one more time. However i am not willing to spend more time than necessary on this one.

**Comment by chitgoks** [comment]
for confirmation, once this gets merged, the auto reload will work?

**Comment by ievgennaida** [comment]
Can it fix this problem?

https://github.com/anthonyjgrove/react-google-login/issues/404

**Comment by rodrigofazenda** [comment]
will it be merged? I would like to use this feature as well.

**Comment by applike-ss** [comment]
we stopped using this mechanism in favour of a different way to authenticate/authorize users, so anyone who wants to take this one over can just create their own PR. Closing this, as i will not be rebasing it or do any other changes to it. Sorry for the late reply.

**Pull request closed without merging**
