### PR TITLE
Added logout and live update according to global google login status.

### PR DESCRIPTION
**Pull request by garajo**
Thanks for solving this problem. I'm not sure how you want to develop this component, but I needed more than being able to login. The global google login status is reflected in the component state and rendered to the UI. You can login/logout of Google in a separate browser, and the component will change accordingly.

### CODE REVIEW

**Comment by anthonyjgrove** [comment]
Thanks for the PR.  Can you give me a little more details into the use case for this so I can figure out how it fits into how I and likely how most people are currently using the component?

**Comment by garajo** [comment]
Sure, I needed to cover these use cases.

1) Have the component know whether the user is logged in or not, upon landing on the page.

2) Being able to logout

3) Detecting if user gets logged on or logged off in another browser, and changing state accordingly.

No worries, if this doesn't work towards most people's use cases.

**Comment by anthonyjgrove** [comment]
I think it would work to have this as a feature of the component but not set as the default. We need to figure out how we would want to implement it though.  What are your thoughts?

**Comment by garajo** [comment]
@anthonyjgrove That sounds really good, and I can work on that. I think there will be several ways to accomplish that. Do you have a direction in mind?

**Comment by garajo** [comment]
I'm reviewing solutions for this. In order to keep it compatible with external state maintainers such as Flux and Redux, this component should not invoke those libraries. This is a good article for patterns to review, http://andrewhfarmer.com/component-communication/

**Comment by anthonyjgrove** [comment]
Ideally it would just use callbacks to send data up, not sure how else you would want to handle this?

**Comment by garajo** [comment]
I'm not sure when a second callback would be triggered, nor what data it would send up. If a logout were included, I was thinking of refactoring the one callback there.

I had two thoughts, neither involved a callback. First option is the simplest; add a property that would toggle whether the components should implement the listen and logout. Or, if `logoutText` is not there, we assume the event listener and logout button should not be included.

The other thought was to make logout a sibling component. This maybe has the slight benefit of being a bit more explicit with the JSX, but could confuse the general implementation. Something like this.

<div>
  <GoogleLogin />

**Comment by garajo** [comment]
Sorry, I cannot work an this anymore.

**Pull request closed without merging**
