### PR TITLE
Added Logout button 

### PR DESCRIPTION
**Pull request by john1jan**
Added a new GoogleLogout component which by clicking logs out using auth2.signOut() method
@anthonyjgrove  Check it once and merge it.

### CODE REVIEW

**Comment by anthonyjgrove** [comment]
would you be able to add some basic tests for logout? as well as fix the linting errors?

Thanks!

**Comment by john1jan** [comment]
Added Basic test and fixed linting errors

**Comment by john1jan** [comment]
@anthonyjgrove check it once.

**Comment by rakks** [comment]
Thanks @john1jan. Can you please give a 2 liner code use <GoogleLogout>. As my below code is still not logging out the user:
<GoogleLogout
                  buttonText="Logout"
                  onLogoutSuccess={this.logout()}
                >
                </GoogleLogout>

**Comment by john1jan** [comment]
```
import { GoogleLogout } from 'react-google-login';
    <GoogleLogout
      buttonText="Logout"
      onLogoutSuccess={logout}
    >
    </GoogleLogout>


logout=()=>{
console.log("logout success")
}

```

**Pull request merged**
