### PR TITLE
Try/Catch when removing container elements on unmount

### PR DESCRIPTION
**Pull request by evantahler**
Removing the elements this login button creates is a neat idea, but depending on how the render chain works for you app, all (child) elements on the page may have already been deleted by the time `componentWillUnmount` gets called.    So to prevent crashes, everything could be in a `try/catch`

This was a particularly obvious issue in next.js projects.

### CODE REVIEW

**Comment by estevanmaito** [comment]
Can confirm this solves the problem.

I don't know what changed in my project (Next.js), but I started to get "Cannot read property 'parenNode" of undefined" errors after login, when I redirect.

I've applied the changes that this commit proposes and it's now solved (and the problem clear to me).

It would be great to have this merged.

It seems that it's also related to these issues:

#146 #131 #59

**Comment by estevanmaito** [comment]
hey @anthonyjgrove 
don't mean to bother, but would you mind reviewing/merging this PR?
sorry for the ping

**Comment by anthonyjgrove** [comment]
Merged, but need to fix a few things with the build/deploy so hope to have it published this weekend

**Comment by noudadrichem** [comment]
This error still occurs in my NextJS project. Everything is latest version and this try/catch code is already in the node module.. Not sure what is going on here. It breaks routing when I change to another page. This component is in my Nav component which I think makes the button re-render. But really not sure how to fix this is all the errors are in the module code.

**Pull request merged**
